# Generated by Django 2.2.6 on 2019-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('track_ref', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('from_coutry', models.CharField(max_length=56)),
                ('to_country', models.CharField(max_length=56)),
                ('package_weight', models.FloatField(max_length=50)),
                ('package_dimensions', models.CharField(max_length=50)),
            ],
        ),
    ]
