# Generated by Django 2.2.6 on 2019-10-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='package_dimensions',
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
