# Generated by Django 2.2.6 on 2019-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20191008_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_up_to_date',
            field=models.BooleanField(default=True, verbose_name='Up to date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_coutry',
            field=models.CharField(max_length=56, verbose_name='Country of dispatch '),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='package_weight',
            field=models.FloatField(max_length=50, verbose_name='Package weight (kg)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_country',
            field=models.CharField(max_length=56, verbose_name='Country of destination'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='track_ref',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='Track code'),
        ),
    ]
